# Generated by Django 6.1.1 on 2026-09-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='log_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('tensorboard', 'TensorBoard')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to='projects.experiment')),
            ],
            options={
                'verbose_name': 'Log file',
                'verbose_name_plural': 'Log files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_types', to='projects.project')),
            ],
            options={
                'verbose_name': 'Measurement type',
                'verbose_name_plural': 'Measurement types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('split', models.CharField(choices=[('train', 'Train'), ('val', 'Validation'), ('test', 'Test')], default='train', max_length=10)),
                ('step', models.PositiveIntegerField()),
                ('step_unit', models.CharField(choices=[('epoch', 'Epoch'), ('iteration', 'Iteration')], default='epoch', max_length=10)),
                ('value', models.FloatField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.experiment')),
                ('log_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainings.logfile')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('split', models.CharField(choices=[('train', 'Train'), ('val', 'Validation'), ('test', 'Test')], default='val', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='projects.experiment')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='SampleMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='trainings.measurementtype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='trainings.sample')),
            ],
            options={
                'verbose_name': 'Sample measurement',
                'verbose_name_plural': 'Sample measurements',
                'ordering': ['measurement_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='measurementtype',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_measurement_type_per_project'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['experiment', 'name', 'split'], name='trainings_m_experim_393065_idx'),
        ),
        migrations.AddIndex(
            model_name='samplemeasurement',
            index=models.Index(fields=['sample', 'measurement_type'], name='trainings_s_sample__5f1f36_idx'),
        ),
    ]
