# Generated by Django 6.1.1 on 2026-09-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_experiment_run_at_and_more'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='fold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SampleMeasurementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sample_measurement_files/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_measurement_files', to='projects.experiment')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_measurement_files', to='trainings.measurementtype')),
            ],
            options={
                'verbose_name': 'Sample measurement file',
                'verbose_name_plural': 'Sample measurement files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
